### ISSUE TITLE
how to install ?

### ISSUE THREAD

**Issue by ghost** [bumrufus/humhub-modules-phonebook#6]
Hello, 
i dream it for years !!

thanks to malke it, but how to install please

**Comment by ghost** [comment]
To install it : 

go in ths directory module : 
cd /var/www/html/humhub/protected/modules

and lunch the command : 
 git clone https://github.com/bumrufus/humhub-modules-phonebook

and go to the module interface to activate 👍 

![image](https://user-images.githubusercontent.com/301074/55218531-a7321400-5202-11e9-843e-7cc4b7a53f66.png)

but when i lunch i have this error : 


![image](https://user-images.githubusercontent.com/301074/55218472-84076480-5202-11e9-8e60-bc1c6b68290b.png)



how fix please

**Comment by ghost** [comment]
i found this error message in journal : 


` Error  Fri, 29 Mar 2019 09:12:22 +0100  yii\base\UnknownPropertyException
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\user\models\Profile::kuerzel in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('kuerzel') #1 /var/www/html/humhub/protected/modules/humhub-modules-phonebook/views/index/index.php(83): yii\db\BaseActiveRecord->__get('kuerzel') #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/h...') #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/h...', Array) #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\phonebook\controllers\IndexController)) #5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\phonebook\controllers\IndexController)) #6 /var/www/html/humhub/protected/modules/humhub-modules-phonebook/controllers/IndexController.php(22): yii\base\Controller->render('index') #7 [internal function]: humhub\modules\phonebook\controllers\IndexController->actionIndex() #8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('phonebook/index', Array) #12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /var/www/html/humhub/index.php(25): yii\base\Application->run() #14 {main} `

**Comment by bumrufus** [comment]
u need to have the base module directory installed and then u have to change the fields here:
https://github.com/bumrufus/humhub-modules-phonebook/blob/ec6ecccb90f2fec0f7ed8465e4100ee56cc9c1fa/views/index/index.php#L26-L35
and here: https://github.com/bumrufus/humhub-modules-phonebook/blob/ec6ecccb90f2fec0f7ed8465e4100ee56cc9c1fa/views/index/index.php#L82-L90

the error messag esays that u donbt have a profile field called kuerzel (it was created by myself) 
look at the screenshots:
https://github.com/bumrufus/humhub-modules-phonebook/blob/master/assets/screen2.jpg

only use fields that exists at your installation

**Comment by bumrufus** [comment]
The fields are located here: Administration -> Users -> Profiles -> select a Profile -> Internal Name
